class Sized:
    def __len__(self) -> int: ...

def len(__obj: Sized) -> int: ...

class list(object):
    @overload
    def append(self, __object: int) -> None: ...
    @overload
    def append(self, __object: str) -> None: ...
    def append(self, __object: object) -> None: ...

class MyClass:
    def my_method(self, x: int) -> int: ...
