[tool.poetry]
name = "python-hover-test"
version = "0.1.0"
description = "Test project for Python hover extension"
authors = ["Developer"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
