export const ALLOWED_MODULE_BROWSER_COMMANDS = new Set([
  "python-hover.searchDocs",
]);

export const ALLOWED_MODULE_BROWSER_SETTING_KEYS = new Set([
  "python-hover.ui.moduleBrowser.defaultSort",
  "python-hover.ui.moduleBrowser.defaultView",
  "python-hover.ui.moduleBrowser.defaultDensity",
  "python-hover.ui.moduleBrowser.showPrivateSymbols",
  "python-hover.ui.moduleBrowser.autoLoadPreviews",
  "python-hover.ui.moduleBrowser.showHierarchyHints",
]);

export const ALLOWED_STUDIO_COMMANDS = new Set([
  "python-hover.searchDocs",
  "python-hover.findMethod",
  "python-hover.browseModule",
  "python-hover.pinLast",
  "python-hover.showHistory",
  "python-hover.toggleLearnMode",
  "python-hover.showTelemetry",
  "python-hover.buildPythonCorpus",
  "python-hover.cancelPythonCorpusBuild",
  "python-hover.clearCache",
  "python-hover.clearStdlibCorpus",
  "python-hover.clearAllCache",
  "python-hover.openCacheFolder",
  "python-hover.showLogs",
]);

export const ALLOWED_STUDIO_SETTING_KEYS = new Set([
  "python-hover.ui.compactMode",
  "python-hover.ui.showToolbar",
  "python-hover.ui.showProvenance",
  "python-hover.ui.showBadges",
  "python-hover.ui.showMetadataChips",
  "python-hover.ui.showSignatures",
  "python-hover.ui.showParameterLens",
  "python-hover.ui.showReturnTypes",
  "python-hover.ui.showCallouts",
  "python-hover.ui.showDescription",
  "python-hover.ui.showParameters",
  "python-hover.ui.showRaises",
  "python-hover.ui.showSeeAlso",
  "python-hover.ui.showNotes",
  "python-hover.ui.showModuleExports",
  "python-hover.ui.showModuleStats",
  "python-hover.ui.showImportHints",
  "python-hover.ui.showFooter",
  "python-hover.ui.maxContentLength",
  "python-hover.maxSnippetLines",
  "python-hover.ui.maxParameters",
  "python-hover.ui.maxExamples",
  "python-hover.ui.maxModuleExports",
  "python-hover.ui.maxSeeAlsoItems",
  "python-hover.ui.hoverSectionOrder",
  "python-hover.showPracticalExamples",
  "python-hover.onlineDiscovery",
  "python-hover.runtimeHelper",
  "python-hover.astFallback",
  "python-hover.docScraping",
  "python-hover.buildFullCorpus",
  "python-hover.warmupImports",
  "python-hover.useKnownDocsUrls",
  "python-hover.diagnostics.enabled",
  "python-hover.enableDebugLogging",
  "python-hover.docsBrowser",
  "python-hover.devdocsBrowser",
  "python-hover.ui.redirectIntegratedHoverToDocsPage",
  "python-hover.ui.autoOpenCurrentHoverInIntegratedDocs",
  "python-hover.ui.learnMode",
  "python-hover.ui.visualStyle",
  "python-hover.telemetry.enabled",
  "python-hover.requestTimeout",
  "python-hover.hoverActivationDelay",
  "python-hover.ui.showStatusBar",
  "python-hover.ui.showDebugPinButton",
  "python-hover.ui.contextMenu.enabled",
  "python-hover.ui.contextMenu.searchDocs",
  "python-hover.ui.contextMenu.browseModule",
  "python-hover.ui.contextMenu.pinHover",
  "python-hover.ui.contextMenu.debugPinHover",
  "python-hover.ui.contextMenu.openStudio",
  "python-hover.ui.moduleBrowser.defaultView",
  "python-hover.ui.moduleBrowser.defaultSort",
  "python-hover.ui.moduleBrowser.defaultDensity",
  "python-hover.ui.moduleBrowser.showPrivateSymbols",
  "python-hover.ui.moduleBrowser.autoLoadPreviews",
  "python-hover.ui.moduleBrowser.showHierarchyHints",
]);

export function allowedSettingsQuery(
  query: string | undefined,
  fallback: string,
): string {
  return query && query.startsWith("python-hover") ? query : fallback;
}
